import { CatalogOrderData } from '@/types/catalog';

export const lashPreset: CatalogOrderData = {
  slug: 'modelo-lash',
  client_name: 'Mariana Alves',
  studio_name: 'Studio Mariana Alves',
  hero_phrase: 'A arte de transformar o seu olhar — leveza incomparável, precisão e elegância.',
  bio_description: 'Especialista em Cílios, Lash Lifting e Visagismo do Olhar.',
  cover_media_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Hero.png',
  avatar_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Hero.png',
  niche: 'lash',
  layout_model: 'mosaico',
  theme_variant: 'rose',
  whatsapp_number: '5562991083435',
  instagram_handle: '@marianaalves.lash',
  address: 'São Paulo',
  instructions_bg_url: 'https://lashmenu.com/modelos/mosaico/assets/img/hero.jpg',
  final_screen_bg_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Footer.png',
  procedures: [
    {
      id: 'l1',
      title: 'Volume Brasileiro',
      description: 'Fios tecnológicos em formato Y que preenchem falhas naturais com leveza incomparável e efeito marcante.',
      price: '150,00',
      duration: '1h30min',
      category: 'Extensão de Cílios',
      badge: 'Mais Pedido',
      is_highlight: true,
      image_url: 'https://images.unsplash.com/photo-1583001809873-a1284d563391?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 'l2',
      title: 'Clássico Fio a Fio',
      description: 'Um fio sintético ultrafino acoplado a cada cílio natural. O resultado mais elegante e discreto com efeito de rímel.',
      price: '120,00',
      duration: '1h30min',
      category: 'Extensão de Cílios',
      image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 'l3',
      title: 'Volume Egípcio',
      description: 'Fios especiais em formato W (3D) que proporcionam densidade homogênea e efeito aveludado.',
      price: '160,00',
      duration: '1h30min',
      category: 'Extensão de Cílios',
      badge: 'Lançamento',
      image_url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=400&q=80',
    },
    {
      id: 'l4',
      title: 'Lash Lifting & Nutrição',
      description: 'Tratamento de curvatura, nutrição profunda com queratina e tintura nos cílios naturais. Zero manutenção.',
      price: '130,00',
      duration: '1h',
      category: 'Especiais & Cuidados',
    },
    {
      id: 'l5',
      title: 'Design de Sobrancelhas + Henna',
      description: 'Mapeamento facial personalizado, alinhamento simétrico e aplicação de henna natural.',
      price: '70,00',
      duration: '45min',
      category: 'Sobrancelhas',
    },
  ],
  instructions: {
    pre_care: [
      'Venha com a região dos olhos sem maquiagem ou rímel.',
      'Evite café ou bebidas estimulantes antes do procedimento.',
    ],
    post_care: [
      'Não molhar a extensão nas primeiras 24 horas.',
      'Higienizar diariamente com shampoo neutro infantil.',
      'Escovar os cílios diariamente com a escovinha fornecida.',
    ],
    tolerances: 'Tolerância máxima de 15 minutos de atraso.',
  },
};
