import { CatalogOrderData } from '@/types/catalog';

export const lashPreset: CatalogOrderData = {
  slug: 'modelo-lash',
  client_name: 'Mariana Alves',
  studio_name: 'Studio Mariana Alves',
  hero_phrase: 'A arte de transformar o seu olhar — leveza incomparável, precisão e elegância.',
  bio_description: 'Especialista em Cílios, Lash Lifting e Visagismo do Olhar.',
  cover_media_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Hero.png',
  avatar_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Hero.png',
  niche: 'lash',
  layout_model: 'mosaico',
  theme_variant: 'rose',
  whatsapp_number: '5562991083435',
  instagram_handle: '@marianaalves.lash',
  address: 'São Paulo',
  instructions_bg_url: 'https://lashmenu.com/modelos/mosaico/assets/img/hero.jpg',
  final_screen_bg_url: 'https://lashmenu.com/modelos/mosaico/assets/img/Footer.png',
  procedures: [
    {
      id: 'brasileiro',
      title: 'Volume Brasileiro',
      description: 'Fios tecnológicos com formato Y que preenchem as falhas naturais com leveza incomparável, alta durabilidade e acabamento marcante.',
      price: 'R$ 150',
      duration: '1h30',
      category: 'Extensão de Cílios',
      badge: 'Mais Pedido',
      is_highlight: true,
      image_url: '/modelos/mosaico/assets/img/volume-brasileiro.png',
    },
    {
      id: 'classico',
      title: 'Clássico Fio a Fio',
      description: 'Um fio sintético ultrafino acoplado a cada cílio natural saudável. O resultado mais elegante e discreto: olhar iluminado com efeito de rímel perfeito.',
      price: 'R$ 120',
      duration: '1h30',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/classico-fio-a-fio.png',
    },
    {
      id: 'egipcio',
      title: 'Volume Egípcio',
      description: 'Fios especiais em formato W (3D tecnológico) que proporcionam densidade homogênea, efeito aveludado e volume equilibrado sem pesar nos olhos.',
      price: 'R$ 160',
      duration: '1h30',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/volume-egipcio.png',
    },
    {
      id: 'hibrido',
      title: 'Volume Híbrido',
      description: 'A combinação artesanal entre a delicadeza do fio a fio clássico e leques de volume, criando textura multidimensional, profundidade e brilho no olhar.',
      price: 'R$ 160',
      duration: '1h45',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/volume-hibrido.png',
    },
    {
      id: 'russo',
      title: 'Volume Russo',
      description: 'Técnica de alta precisão com fans ultrafinos (3 a 6 fios de seda) montados à mão na hora. Cria um volume expressivo, extremamente macio, denso e sofisticado.',
      price: 'R$ 190',
      duration: '2h00',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/volume-russo.png',
    },
    {
      id: 'mega',
      title: 'Mega Volume',
      description: 'O ápice da densidade e do impacto visual: leques artesanais com fios ultrafinos de 0.03mm. Proporciona um olhar super pretinho, aveludado e hipnotizante.',
      price: 'R$ 240',
      duration: '2h30',
      category: 'Extensão de Cílios',
      badge: 'Densidade Máxima',
      is_highlight: true,
      image_url: '/modelos/mosaico/assets/img/mega-volume.png',
    },
    {
      id: 'gatinho',
      title: 'Mapping Gatinho',
      description: 'Crescimento milimétrico dos fios em direção ao canto externo. Alonga o olhar, cria um efeito felino refinado e valoriza o contorno dos olhos.',
      price: 'Incluso',
      duration: 'Design',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/mapping-gatinho.png',
    },
    {
      id: 'boneca',
      title: 'Mapping Boneca',
      description: 'Fios com maior comprimento posicionados estrategicamente no centro da íris. Abre e ilumina o olhar, proporcionando aspecto doce, expressivo e jovial.',
      price: 'Incluso',
      duration: 'Design',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/mapping-boneca.png',
    },
    {
      id: 'esquilo',
      title: 'Mapping Esquilo',
      description: 'Pico de comprimento posicionado exatamente no arco da sobrancelha (ponto alto). Disfarça pálpebra caída e cria um efeito de lifting imediato.',
      price: 'Incluso',
      duration: 'Design',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/mapping-esquilo.png',
    },
    {
      id: 'fox',
      title: 'Fox Eyes Signature',
      description: 'O desenho de maior sucesso do estúdio: extremidade externa esticada e alinhada com mapping milimétrico para um visual sensual, moderno e marcante.',
      price: 'R$ 170',
      duration: '1h45',
      category: 'Extensão de Cílios',
      image_url: '/modelos/mosaico/assets/img/fox-eyes.png',
    },
    {
      id: 'design-sobrancelha',
      title: 'Design de Sobrancelha',
      description: 'Mapeamento facial minucioso baseado nas proporções únicas do seu rosto, seguido de epilação precisa para realçar sua beleza natural com simetria e elegância.',
      price: 'R$ 60',
      duration: '45min',
      category: 'Sobrancelhas',
      badge: 'Visagismo Facial',
      is_highlight: true,
      image_url: '/modelos/mosaico/assets/img/design-sobrancelha.jpg',
    },
    {
      id: 'sobrancelha-henna',
      title: 'Sobrancelha com Henna',
      description: 'Design personalizado acompanhado de aplicação de Henna orgânica de altíssima fixação. Preenche falhas, define o contorno com efeito ombré natural e destaca o olhar.',
      price: 'R$ 80',
      duration: '50min',
      category: 'Sobrancelhas',
      image_url: '/modelos/mosaico/assets/img/sobrancelha-henna.jpg',
    },
    {
      id: 'lifting',
      title: 'Lash Lifting & Nutrição',
      description: 'Tratamento de curvatura, nutrição profunda com queratina e tintura preta nos seus próprios cílios naturais. Zero manutenção e durabilidade de 6 a 8 semanas.',
      price: 'R$ 130',
      duration: '1h00',
      category: 'Especiais & Cuidados',
      image_url: '/modelos/mosaico/assets/img/lash-lifting.png',
    },
    {
      id: 'remocao',
      title: 'Remoção Segura',
      description: 'Remoção química indolor realizada com gel removedor profissional específico que dissolve o adesivo sem tracionar ou danificar nenhum fio natural.',
      price: 'R$ 50',
      duration: '30min',
      category: 'Especiais & Cuidados',
      image_url: '/modelos/mosaico/assets/img/remocao.png',
    },
    {
      id: 'cuidados',
      title: 'Cuidados Pós-Aplicação',
      description: 'Orientações práticas para prolongar a retenção dos seus cílios: evitar água nas primeiras 24h, higienizar com shampoo neutro e escovar diariamente.',
      price: 'Guia',
      duration: 'Diário',
      category: 'Especiais & Cuidados',
      image_url: '/modelos/mosaico/assets/img/cuidados.jpg',
    },
  ],
  instructions: {
    pre_care: [
      'Venha com a região dos olhos sem maquiagem ou rímel.',
      'Evite café ou bebidas estimulantes antes do procedimento.',
    ],
    post_care: [
      'Não molhar a extensão nas primeiras 24 horas.',
      'Higienizar diariamente com shampoo neutro infantil.',
      'Escovar os cílios diariamente com a escovinha fornecida.',
    ],
    tolerances: 'Tolerância máxima de 15 minutos de atraso.',
  },
};
